site_name: LuminoDocs

nav:
  - Introducción: index.md
  - Requisitos: requeriments.md
  - Instalación: installation.md
  - Diseño: system-design.md
  - Implementación: implementation.md
  - Tests: tests.md
  - Mantenimiento y Actualización: maintanance.md
  - Conclusión y Futuro: our-future.md

theme:
  name: material
